from __future__ import annotations

from enum import Enum


class TaskState(str, Enum):
    IDLE = "IDLE"
    CHECK_SYSTEM = "CHECK_SYSTEM"
    MOVE_HOME = "MOVE_HOME"
    MOVE_TO_PRE_GRASP = "MOVE_TO_PRE_GRASP"
    MOVE_TO_GRASP = "MOVE_TO_GRASP"
    CLOSE_GRIPPER = "CLOSE_GRIPPER"
    VERIFY_GRASP = "VERIFY_GRASP"
    LIFT_WRENCH = "LIFT_WRENCH"
    MOVE_TO_PRE_NUT = "MOVE_TO_PRE_NUT"
    APPROACH_NUT = "APPROACH_NUT"
    SEARCH_ALIGNMENT = "SEARCH_ALIGNMENT"
    SEAT_WRENCH = "SEAT_WRENCH"
    TIGHTEN = "TIGHTEN"
    VERIFY_TIGHTEN = "VERIFY_TIGHTEN"
    LOOSEN = "LOOSEN"
    VERIFY_LOOSEN = "VERIFY_LOOSEN"
    RETRACT = "RETRACT"
    MOVE_TO_PRE_PLACE = "MOVE_TO_PRE_PLACE"
    PLACE_WRENCH = "PLACE_WRENCH"
    OPEN_GRIPPER = "OPEN_GRIPPER"
    RETURN_HOME = "RETURN_HOME"
    COMPLETE = "COMPLETE"
    ERROR = "ERROR"
    EMERGENCY_STOP = "EMERGENCY_STOP"
